;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-forward-char
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-previous-visual-line
        helm-confirm-and-exit-minibuffer
        keyboard-quit
        mode-line-minor-mode-help
        text-scale-adjust
        ))

(setq mc/cmds-to-run-once
      '(
        electric-newline-and-maybe-indent
        evil-next-visual-line
        evil-search-forward
        evil-switch-to-windows-last-buffer
        evil-yank
        handle-select-window
        helm-M-x
        ibuffer
        ido-find-file
        ido-switch-buffer
        isearch-printing-char
        mouse-minor-mode-menu
        mouse-select-window
        ))
